# Generated by Django 4.2.4 on 2023-08-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_can_add_to_que',
            field=models.BooleanField(default=False),
        ),
    ]
